//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitchBot.Data {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class TwitchChatCommands : global::System.Configuration.ApplicationSettingsBase {
        
        private static TwitchChatCommands defaultInstance = ((TwitchChatCommands)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TwitchChatCommands())));
        
        public static TwitchChatCommands Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!")]
        public string CommandStart {
            get {
                return ((string)(this["CommandStart"]));
            }
            set {
                this["CommandStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("add")]
        public string AddDeath {
            get {
                return ((string)(this["AddDeath"]));
            }
            set {
                this["AddDeath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("remove")]
        public string RemoveDeath {
            get {
                return ((string)(this["RemoveDeath"]));
            }
            set {
                this["RemoveDeath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("boss")]
        public string StartBoss {
            get {
                return ((string)(this["StartBoss"]));
            }
            set {
                this["StartBoss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pause")]
        public string PauseBoss {
            get {
                return ((string)(this["PauseBoss"]));
            }
            set {
                this["PauseBoss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("end")]
        public string EndBoss {
            get {
                return ((string)(this["EndBoss"]));
            }
            set {
                this["EndBoss"] = value;
            }
        }
    }
}
